services:
  etcd:
    image: m.daocloud.io/quay.io/coreos/etcd:v3.6.1
    command: 
      - /usr/local/bin/etcd
      - --name=node0
      - --auto-compaction-retention=1
      - --quota-backend-bytes=8589934592
      - --data-dir=/var/lib/etcd
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=node0=http://0.0.0.0:2380
    ports:
      - "2379:2379"
    restart: unless-stopped
